app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("project/", views.project_main, name="project"),
    path("client/", views.client, name="client"),
    path("project/create/", views.new_project, name="new_project"),
    path("project/details/", views.project_details, name="project_details"),
    path("client/details/", views.client_details, name="client_details"),
    path("client/manage/", views.manage_client, name="manage_client"),
]

project2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.

MyManager

class MyManager(BaseUserManager):
    def create_user(self,email,username,password=None):
        if not email:
            raise ValueError("User must have an eamil address")
        if not username:
            raise ValueError("User must have an username")
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self,email,username,password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class LoginModel(AbstractBaseUser):
    username = models.CharField(max_length=30,unique=True)
    email = models.EmailField(verbose_name="email",max_length=255,unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined",auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login",auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    password = models.CharField(max_length=16,default="")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyManager()

    def has_perm(self,perm,obj=None):
        return self.is_admin
    def has_module_perms(self,perm,obj=None):
        return True


class Client(models.Model):
    userid = models.ForeignKey(LoginModel,on_delete=models.CASCADE)
    names = models.CharField(max_length=255)
    CompanyName = models.CharField(max_length=255)
    Phone = models.CharField(max_length=255)
    email = models.EmailField()
    def __str__(self):
        return f"Client |name - {self.names} and {self.CompanyName}|"
class project(models.Model):
    userid = models.ForeignKey(LoginModel,on_delete=models.CASCADE)
    ClientId = models.ForeignKey(Client,on_delete=models.CASCADE)
    ProjectId = models.IntegerField()
    Title = models.CharField(max_length=255,blank=False)
    Department = models.CharField(max_length=64,blank=False)
    Status =  models.CharField(max_length=16,blank=False)
    Priority = models.CharField(max_length=16,blank=False)
    From = models.DateTimeField()
    to = models.DateTimeField()
    def __str__(self):
        return f"Project |title - {self.Title} ProjectId - {self.ProjectId}|"

app/forms.py
from django import forms
import re
from .models import LoginModel,Client,project
from django.contrib.auth.forms import UserCreationForm
import datetime
DEPARTMENT_CHOICE = [
    ("Development Department","Development Department"),
    ("Managers Department","Managers Department"),
    ("Application Department","Application Department"),
    ("Accounts Department","Accounts Department")
]
PRIORITY_CHOICE = [
    ("High","High"),
    ("Medium","Medium"),
    ("Low","Low")
]
STATUS_CHOICE = [
    ("Completed","Completed"),
    ("Pending","Pending"),
    ("On Progress","On Progress")
]


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['names','CompanyName','Phone','email']


class ProjectForm(forms.ModelForm):
    client = forms.CharField(widget=forms.Select())
    class Meta:
        model = project
        fields = ['ProjectId','Title','Department','Status','Priority','From','to','client']

    def clean_From(self):
        see = self.cleaned_data['From'].date().year
        year_today = datetime.date.today().year
        if see < year_today:
            raise forms.ValidationError(f"Year must be between {year_today} to {year_today + 5}")
        return self.cleaned_data['From']
    def clean_to(self):
        see = self.cleaned_data['to'].date().year
        year_today = datetime.date.today().year
        if see < year_today:
            raise forms.ValidationError(f"Year must be between {year_today} to {year_today + 5}")
        return self.cleaned_data['to']




class LoginForm(forms.Form):
    email = forms.EmailField(max_length=255,label="Email Id", widget = forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(min_length=8,max_length=16,label="Password", widget = forms.PasswordInput(attrs={'class': 'form-control'}))

class RegForm(UserCreationForm):
    username = forms.CharField(min_length=4,max_length=255,label="Username", widget = forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=255,label="Email Id", widget = forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(min_length=8,max_length=16,label="Password", widget = forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(min_length=8,max_length=16,label="Re Enter Password", widget = forms.PasswordInput(attrs={'class': 'form-control'}), help_text = "Enter the same password as above, for verification.")

    class Meta:
        model = LoginModel
        fields = ['username','email','password1','password2']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""


    def clean(self):
        super(RegForm, self).clean()
        # print ("here is " + str(self.cleaned_data))
        try:
            password = self.cleaned_data['password1']
        except:
            password = ""
        try:
            pass2 = self.cleaned_data['password2']
        except:
            pass2 = ""


        pattern = re.compile('[A-Z]')
        pattern2 = re.compile('[a-z]')
        pattern3 = re.compile('[0-9]')
        pattern4 = re.compile('[!@#$%^&*(),.?":{}|<>]')

        if not pattern.search(password) or not pattern2.search(password) or not pattern3.search(password) or not pattern4.search(password):
                list = ['should contain at least one upper case','should contain at least one lower case','should contain at least one digit','should contain at least one Special character']
                self.add_error('password1',list)
                try:
                    del self._errors['password2']
                except:
                    pass

        else:
            if password != pass2:
                error_message = 'Password did not matched. Enter the same password as above'
                field = 'password2'
                # if self._errors['password2']:
                #     del self._errors['password2']
                try:
                    del self._errors['password2']
                except:
                    pass
                self.add_error(field,error_message)
        return self.cleaned_data




    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = LoginModel.objects.get(email=email)
        except:
            return email
        raise forms.ValidationError(f"Email {email} is already in use.")
        

    def clean_username(self):
        username = self.cleaned_data['username']
        print("username "+ str(username))
        try:
            user_name = LoginModel.objects.get(username=username)
        except:
            return username
        raise forms.ValidationError(f"Username {username} is already in use.")

app/templates/page/client-details.html
{% extends "main.html" %}
{% block title %}Client-details{% endblock %}
{% block body %}
  <main>
    {% if success %}
    <div class="alert alert-primary" role="alert">
      {{success}}
    </div>
    {% endif %}
    {% if fail %}
    <div class="alert alert-danger" role="alert">
      <p>{{fail}}</p>
      {% for field in form%}
      {% if field.errors%}
      <h6 class="test-size-custom">{{field.label_tag}}</h6>
      <ul class="test-size-custom">
      {% for error in field.errors%}
      <li>{{error}}</li>
      {% endfor %}
    </ul>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <div class="container">

    {% for obj in client %}
    <ul class="list-group">
    <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-primary">
    <h2>Client - {{obj.1.names}}</h2>
    <span class="badge bg-primary rounded-pill">{{obj.3}}</span>
    </li>
    </ul>
    <hr>
    <ol type="1" class="bg-light px-5 pt-3 pb-3"> 
    {% for i in obj.2 %}
    {% for m in i %}
    <li><h5>Project Details</h5></li>
    <ul class="list-group list-group-horizontal-lg">
    <li class="list-group-item" >PROJECT ID - {{m.ProjectId}}</li>
    <li class="list-group-item" >TITLE - {{m.Title}}</li>
    </ul>
    <ul class="list-group list-group-horizontal-lg">
    <li class="list-group-item" >PRIORITY - {{m.Priority}}</li>
    <li class="list-group-item" >DURATION - {{m.From}} to {{m.to}}</li>
    </ul>
    {% endfor %}
    {% endfor %}
    </ol>
    {% endfor %}
</div>
  </main>
  <footer>
    <!-- place footer here -->
  </footer>
{% endblock %}

app/templates/page/client.html
{% extends "main.html" %}
{% block title %}Client{% endblock %}
{% block body %}
  <main>
    {% if success %}
    <div class="alert alert-primary" role="alert">
      {{success}}
    </div>
    {% endif %}
    {% if fail %}
    <div class="alert alert-danger" role="alert">
      <p>{{fail}}</p>
      {% for field in form%}
      {% if field.errors%}
      <h6 class="test-size-custom">{{field.label_tag}}</h6>
      <ul class="test-size-custom">
      {% for error in field.errors%}
      <li>{{error}}</li>
      {% endfor %}
    </ul>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <div class="container pt-3">
     <div class="row bg-white p-2 border">
      <div class="col-md-8 col-sm-6 col-auto">
                    <div class="row rounded text-bg-custom text-width-custom p-2">
                      <div class="col-3">
                        <i class="fa fa-briefcase" aria-hidden="true"></i>
                      </div>
                    <div class="col-9 test-size-custom">
                    <div>
                      Total Client
                    </div>
                      <div>
                        <strong style="color: blue;">{{client}}</strong>
                    </div>
                  </div>
                  </div>
      </div>
      <div class="col-md-4 col-sm-6 col-auto">
      <li class="list-group-item" ><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
        &#43; ADD NEW CLIENTS
    </button></li>
  </div>
</div>
</div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <form action="/client/" method="post">
              {% csrf_token %}
            <div>
              <label class="form-label" for="id_names">Names:</label>
              <input class="form-control" type="text" name="names" maxlength="255" required id="id_names">
            </div>
            <div>
              <label class="form-label" for="id_CompanyName">CompanyName:</label>
              <input class="form-control" type="text" name="CompanyName" maxlength="255" required id="id_CompanyName">
            </div>
            <div>
              <label class="form-label" for="id_Phone">Phone:</label>
              <input class="form-control" type="text" name="Phone" maxlength="255" required id="id_Phone">
            </div>
            <div>
              <label class="form-label" for="id_email">Email:</label>
              <input class="form-control" type="email" name="email" maxlength="254" required id="id_email">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
          </div>
        </div>
      </div>
    </div>



  </main>
  <footer>
    <!-- place footer here -->
  </footer>
{% endblock %}

app/templates/page/home.html
{% extends 'main.html' %}
{% block title %}HOME{% endblock %}
{% block body %}
{% endblock %}

app/templates/page/login.html
<!doctype html>
<html lang="en">

<head>
  <title>Title</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>
<style>
  .custom-container{
    max-width: 300px;
    margin: auto;
  }
  #span-error{
    font-size:10px;
  }
  form input[type="submit"]{
    background-color: green;
    color: aliceblue;
  }
  #image{
    padding-left: calc(50% - 45px);
    /* margin-left: auto; */
  }
</style>
<body>
  <header>
    <!-- place navbar here -->
  </header>
  <main>


    <div class="custom-container">
      <div id = "image">
        <img src="https://www.loudegg.com/wp-content/uploads/2020/10/SpongeBob-SqaurePants.jpg" height="120px" alt="SpongeBob SquarePants">
      </div>
    <form action="/login/" method="post">
      {% csrf_token %}
      {% if nologin%}
      <div class="alert alert-primary">{{nologin}}</div>
      {% endif %}
        {{form.non_field_errors}}
        {% for field in form %}
        <div> {{field.label_tag}} {{field}}
          <ul>
        {% for error in field.errors %}
        <li id="span-error"><span  class="text-muted">{{error}}</span></li>
        {% endfor %}
      </ul>
        </div>
        {% endfor %}
    <input class="form-control" type="submit" value="Submit">
</form>
<a href={% url 'signup'%}><button type="button" class="btn btn-primary form-control mt-2">Signup</button></a>
</div>
  </main>
  <footer>
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>

app/templates/page/manage-client.html
{% extends "main.html" %}
{% block title %}Manage-Client{% endblock %}
{% block body %}

  <main>
    {% if success %}
    <div class="alert alert-primary" role="alert">
      {{success}}
    </div>
    {% endif %}
    {% if fail %}
    <div class="alert alert-danger" role="alert">
      <p>{{fail}}</p>
      {% for field in form%}
      {% if field.errors%}
      <h6 class="test-size-custom">{{field.label_tag}}</h6>
      <ul class="test-size-custom">
      {% for error in field.errors%}
      <li>{{error}}</li>
      {% endfor %}
    </ul>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <h2 style="text-align: center;">CLIENT DETAILS</h2>
{% for i in client %}
<ul class="list-group p-3">
    <li class="list-group-item" >Client Name - {{i.names}}</li>
    <li class="list-group-item" >Company Name - {{i.CompanyName}}</li>
    <li class="list-group-item" >Phone Number - {{i.Phone}}</li>
    <li class="list-group-item" >Email ID - {{i.email}}</li>
</ul>
{% endfor %}


  </main>
  <footer>
    <!-- place footer here -->
  </footer>

{% endblock %}

app/templates/page/new-project.html
{% extends "main.html" %}
{% block title %}Create-Project{% endblock %}
{% block body %}


  <main>
    {% if success %}
    <div class="alert alert-primary" role="alert">
      {{success}}
    </div>
    {% endif %}
    {% if fail %}
    <div class="alert alert-danger" role="alert">
      <p>{{fail}}</p>
      {% for field in form%}
      {% if field.errors%}
      <h6 class="test-size-custom">{{field.label_tag}}</h6>
      <ul class="test-size-custom">
      {% for error in field.errors%}
      <li>{{error}}</li>
      {% endfor %}
    </ul>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <div class="container">
    <form action="/project/create/" method="post">
        {% csrf_token %}
    <div class="row">
        <div class="col-6">
          <div>
          <label for="id_ProjectId">Project ID</label>
          <input class="form-control" type="number" name="ProjectId" value="{{form.ProjectId.value }}" required id="id_ProjectId">
        </div>
        {% for error in form.ProjectId.errors %}
        <div class="form-text"> {{ error }} </div>
        {% endfor %}
        <div>
          <label for="id_Department" >Department:</label>
          <select class="form-control"  name="Department" id="id_Department" required >
          <option value="" disabled selected>Select your option</option>
          <option value="Development Department">Development Department</option>
          <option value="Managers Department">Managers Department</option>
          <option value="Application Department">Application Department</option>
          <option value="Accounts Department">Accounts Department</option>
        </select>
        {% for error in form.Department.errors %}
        <div class="form-text"> {{ error }} </div>
        {% endfor %}
          </div>
          <div>
            <label for="id_client">Client:</label>
            <select class="form-control" name="client" id="id_client" required>
              <option value="" disabled selected>Select your option</option>
              {% for i in client%}
            <option value={{i.id}}>{{i.names}}</option>
              {% endfor %}
          </select>
          {% for error in form.client.errors %}
          <div class="form-text"> {{ error }} </div>
          {% endfor %}
        </div>
        </div>
        <div class="col-6">
          <div>
            <label for="id_Title">Title:</label>
            <input class="form-control" name="Title" value="{{form.Title.value }}" required  >
          </div>
          {% for error in form.Title.errors %}
          <div class="form-text"> {{ error }} </div>
          {% endfor %}
          <div>
            <label for="id_Priority">Priority:</label></th>
            <select class="form-control" name="Priority" id="id_Priority" required >
              <option value="" disabled selected>Select your option</option>
              <option value="High">High</option>
              <option value="Medium">Medium</option>
              <option value="Low">Low</option>
            </select> 
            {% for error in form.Priority.errors %}
            <div class="form-text"> {{ error }} </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          <label for="id_From">From:</label>
          <input class="form-control" type="datetime-local" name="From" required id="id_From" value="{{form.From.value }}" >
          {% for error in form.From.errors %}
          <div class="form-text"> {{ error }} </div>
          {% endfor %}
        </div>

        <div class="col-6">
          <label for="id_to">To:</label>
          <input class="form-control" type="datetime-local" name="to" required id="id_to" value="{{form.to.value }}" >
          {% for error in form.to.errors %}
          <div class="form-text"> {{ error }} </div>
          {% endfor %}
        </div>

      </div>


      <div class="row pt-3 pb-3">
        <div class="col-sm-3">
          <label>Work Status:</label>
        </div>
        
        <div class="form-check col-sm-3" id="id_Status">
          <input class="form-check-input" type="radio" name="Status" value="Completed" required id="id_Status_0">
          <label class="form-check-label" for="id_Status_0">Completed</label>
        </div>
        <div class="form-check col-sm-3" id="id_Status">
          <input class="form-check-input" type="radio" name="Status" value="Pending" required id="id_Status_1">
          <label class="form-check-label" for="id_Status_1">Pending</label>
        </div>
        <div class="form-check col-sm-3" id="id_Status">
          <input class="form-check-input" type="radio" name="Status" value="On Progress" required id="id_Status_2">
          <label class="form-check-label" for="id_Status_2">On Progress</label>
        </div>
      </div>
        <button type="Submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
  </main>
  <footer>
    <!-- place footer here -->
  </footer>
{% endblock %}

app/templates/page/project-details.html
{% extends "main.html" %}
{% block title %}Project-Details{% endblock %}
{% block body %}
  <main>
    {% if success %}
    <div class="alert alert-primary" role="alert">
      {{success}}
    </div>
    {% endif %}
    {% if fail %}
    <div class="alert alert-danger" role="alert">
      <p>{{fail}}</p>
      {% for field in form%}
      {% if field.errors%}
      <h6 class="test-size-custom">{{field.label_tag}}</h6>
      <ul class="test-size-custom">
      {% for error in field.errors%}
      <li>{{error}}</li>
      {% endfor %}
    </ul>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <h2 style="text-align: center;">PROJECT DETAILS</h2>
    {% for i in data %}
    <ul class="list-group p-3">
        <li class="list-group-item" >Project ID - {{i.ProjectId}}</li>
        <li class="list-group-item" >Title - {{i.Title}}</li>
        <li class="list-group-item" >Department - {{i.Department}}</li>
        <li class="list-group-item" >Status - {{i.Status}}</li>
        <li class="list-group-item" >Priority - {{i.Priority}}</li>
        <li class="list-group-item" >Duration - {{i.From}} to {{i.To}}</li>
    </ul>
    {% endfor %}
  </main>
  <footer>
    <!-- place footer here -->
  </footer>

{% endblock %}

app/templates/page/project.html
{% extends "main.html" %}
{% block title %}Project{% endblock %}
{% block body %}
  <main>
    {% if success %}
    <div class="alert alert-primary" role="alert">
      {{success}}
    </div>
    {% endif %}
    {% if fail %}
    <div class="alert alert-danger" role="alert">
      <p>{{fail}}</p>
      {% for field in form%}
      {% if field.errors%}
      <h6 class="test-size-custom">{{field.label_tag}}</h6>
      <ul class="test-size-custom">
      {% for error in field.errors%}
      <li>{{error}}</li>
      {% endfor %}
    </ul>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
<div class="container pt-3">
  <div class="row bg-white p-2 border justify-content-sm-between">
            <div class="col-sm-auto mt-1 mb-1" >
                  <div class="rounded box-custom p-2 col-9 ">
                  <div>
                    Total Projects
                  </div>
                    <div>
                      <strong style="color: blue;">{{dataTotal}}</strong>
                  </div>
                </div>
          </div>
          <div class="col-sm-auto mt-1 mb-1">
                  <div class="rounded box-custom p-2 col-9">
                 <div>
                   Pending projects
                 </div>
                   <div>
                     <strong style="color: blue;">{{dataPending}}</strong>
               </div>
          </div>
          </div>
          <div class="col-sm-auto mt-1 mb-1">
                  <div class="rounded box-custom p-2 col-9">
                  <div>
                    Ongoing Projects
                  </div>
                    <div>
                      <strong style="color: blue;">{{dataProgress}}</strong>
                  </div>
                </div>
          </div>
          <div class="col-sm-auto mt-1 mb-1">
                  <div class="rounded p-2 col-9 box-custom ">
                  <div>
                    Complete Projects
                  </div>
                    <div>
                      <strong style="color: blue;">{{dataCompleted}}</strong>
                  </div>
                </div>
          </div>
          <div class="col-sm-auto pt-sm-2">
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                &#43; ADD NEW CLIENTS
              </button>
          </div>
      </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <form action="/project/" method="post">
          {% csrf_token %}
      <div class="row">
          <div class="col-6">
            <div>
            <label for="id_ProjectId">Project ID</label>
            <input class="form-control" type="number" name="ProjectId" value="{{form.ProjectId.value }}" required id="id_ProjectId">
          </div>
          {% for error in form.ProjectId.errors %}
          <div class="form-text"> {{ error }} </div>
          {% endfor %}
          <div>
            <label for="id_Department" >Department:</label>
            <select class="form-control"  name="Department" id="id_Department" required >
            <option value="" disabled selected>Select your option</option>
            <option value="Development Department">Development Department</option>
            <option value="Managers Department">Managers Department</option>
            <option value="Application Department">Application Department</option>
            <option value="Accounts Department">Accounts Department</option>
          </select>
          {% for error in form.Department.errors %}
          <div class="form-text"> {{ error }} </div>
          {% endfor %}
            </div>
            <div>
              <label for="id_client">Client:</label>
              <select class="form-control" name="client" id="id_client" required>
                <option value="" disabled selected>Select your option</option>
                {% for i in client %}
              <option value={{i.id}}>{{i.names}}</option>
                {% endfor %}
            </select>
            {% for error in form.client.errors %}
            <div class="form-text"> {{ error }} </div>
            {% endfor %}
          </div>
          </div>
          <div class="col-6">
            <div>
              <label for="id_Title">Title:</label>
              <input class="form-control" name="Title" value="{{form.Title.value }}" required  >
            </div>
            {% for error in form.Title.errors %}
            <div class="form-text"> {{ error }} </div>
            {% endfor %}
            <div>
              <label for="id_Priority">Priority:</label></th>
              <select class="form-control" name="Priority" id="id_Priority" required >
                <option value="" disabled selected>Select your option</option>
                <option value="High">High</option>
                <option value="Medium">Medium</option>
                <option value="Low">Low</option>
              </select> 
              {% for error in form.Priority.errors %}
              <div class="form-text"> {{ error }} </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <label for="id_From">From:</label>
            <input class="form-control" type="datetime-local" name="From" required id="id_From" value="{{form.From.value }}" >
            {% for error in form.From.errors %}
            <div class="form-text"> {{ error }} </div>
            {% endfor %}
          </div>
  
          <div class="col-6">
            <label for="id_to">To:</label>
            <input class="form-control" type="datetime-local" name="to" required id="id_to" value="{{form.to.value }}" >
            {% for error in form.to.errors %}
            <div class="form-text"> {{ error }} </div>
            {% endfor %}
          </div>
  
        </div>
  
  
        <div class="row pt-3 pb-3">
          <div class="col-sm-3">
            <label>Work Status:</label>
          </div>
          
          <div class="form-check col-sm-3" id="id_Status">
            <input class="form-check-input" type="radio" name="Status" value="Completed" required id="id_Status_0">
            <label class="form-check-label" for="id_Status_0">Completed</label>
          </div>
          <div class="form-check col-sm-3" id="id_Status">
            <input class="form-check-input" type="radio" name="Status" value="Pending" required id="id_Status_1">
            <label class="form-check-label" for="id_Status_1">Pending</label>
          </div>
          <div class="form-check col-sm-3" id="id_Status">
            <input class="form-check-input" type="radio" name="Status" value="On Progress" required id="id_Status_2">
            <label class="form-check-label" for="id_Status_2">On Progress</label>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>

        </div>
      </div>
    </div>
  </div>



  </main>
  <footer>
    <!-- place footer here -->
  </footer>
{% endblock %}